blank_issues_enabled: false
contact_links: []
issue_templates:
  - name: 기능 개발 이슈
    description: 기능 기획부터 구현까지 포함하는 이슈 템플릿
    file: feature_issue.md

  - name: 버그 리포트
    description: 발생한 버그를 보고하고 수정 요청
    file: bug_report.md

  - name: 문서 요청
    description: 문서 추가 또는 수정이 필요한 경우
    file: docs_request.md
